// tb.cpp — Testbench for gesture_stream that reads data_with_logits.csv
// Feeds each 20-timestep window into the AXI stream, checks predictions,
// and compares HLS fixed-point logits against Python float reference logits.
//   1. Argmax (top-1) accuracy
//   2. Top-2 accuracy  — correct label in top-2 predictions
//   3. Confidence margin — winner logit minus runner-up logit
//   4. Softmax probability of the predicted class
//   5. Dead-output warning — if all logits are near-zero
//   6. Low-confidence warning — if margin < MARGIN_THRESHOLD
//
// Summary at end:
//   - Top-1 / Top-2 accuracy counts
//   - Per-class confusion: expected vs predicted tally
//   - Min / max / average confidence margin across all samples

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <cmath>
#include <cstdint>
#include <vector>
#include <algorithm>
#include <iomanip>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

// ─── Constants (must match rnn_hls.cpp) ──────────────────────────────────────
#define T_STEPS          20
#define INPUT_SIZE       10
#define NUM_CLASSES       9
#define WEIGHT_SCALE  65536.0f

// Thresholds for logit health checks
#define DEAD_THRESHOLD    0.01f   // max |logit| below which output is "dead"
#define MARGIN_THRESHOLD  0.5f    // min winner-runnerup gap to be "confident"

typedef ap_axis<32,2,5,6> AXIS_wLAST;

// Declaration of the DUT
void gesture_stream(
    hls::stream<AXIS_wLAST>& input_stream,
    hls::stream<AXIS_wLAST>& output_stream
);

// ─── Helper: pack float bits into int32 ──────────────────────────────────────
static inline int32_t float_to_bits(float v) {
    union { float f; int32_t i; } u;
    u.f = v;
    return u.i;
}

// ─── Softmax over NUM_CLASSES logits ─────────────────────────────────────────
static void softmax(const float logits[NUM_CLASSES], float probs[NUM_CLASSES]) {
    float mx = logits[0];
    for (int i = 1; i < NUM_CLASSES; i++) if (logits[i] > mx) mx = logits[i];
    float sum = 0.0f;
    for (int i = 0; i < NUM_CLASSES; i++) { probs[i] = std::exp(logits[i] - mx); sum += probs[i]; }
    for (int i = 0; i < NUM_CLASSES; i++) probs[i] /= sum;
}

// ─── Run one inference on a 30×10 float window ───────────────────────────────
// Returns the argmax class index; fills logits_out[NUM_CLASSES].
int run_inference(float window[T_STEPS][INPUT_SIZE], float logits_out[NUM_CLASSES]) {
    hls::stream<AXIS_wLAST> in_s("in_s");
    hls::stream<AXIS_wLAST> out_s("out_s");

    // Push 30 × 10 floats into the input stream
    for (int t = 0; t < T_STEPS; t++) {
        for (int f = 0; f < INPUT_SIZE; f++) {
            AXIS_wLAST pkt;
            pkt.data = float_to_bits(window[t][f]);
            pkt.last = (t == T_STEPS-1 && f == INPUT_SIZE-1) ? 1 : 0;
            pkt.keep = -1;
            pkt.strb = -1;
            in_s.write(pkt);
        }
    }

    // Call the DUT
    gesture_stream(in_s, out_s);

    // Read 9 logits and dequantize
    int pred = 0;
    float best = -1e30f;
    for (int i = 0; i < NUM_CLASSES; i++) {
        AXIS_wLAST pkt = out_s.read();
        logits_out[i] = (float)((int32_t)pkt.data) / WEIGHT_SCALE;
        if (logits_out[i] > best) { best = logits_out[i]; pred = i; }
    }
    return pred;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
int main() {
    // Open data_with_logits.csv (generated by: python rnn.py --gen-testdata)
    // Columns: gesture_id,timestep,label,name,ax..mag(10),exp_logit_0..8(9)
    std::ifstream csv("data_with_logits.csv");
    if (!csv.is_open()) {
        std::cerr << "ERROR: cannot open data_with_logits.csv\n"
                  << "  Run: python rnn.py --gen-testdata  (from project root)\n";
        return 1;
    }

    // Skip header
    std::string line;
    std::getline(csv, line);

    struct Row {
        float feat[INPUT_SIZE];        // ax..mag  (10 features)
        int   label;                   // gesture class ID
        float exp_logit[NUM_CLASSES];  // Python float reference logits
    };
    std::vector<Row> rows;

    while (std::getline(csv, line)) {
        if (line.empty()) continue;
        std::istringstream ss(line);
        std::string tok;
        Row r;
        // Col 0: gesture_id  (skip)
        std::getline(ss, tok, ',');
        // Col 1: timestep    (skip)
        std::getline(ss, tok, ',');
        // Col 2: label
        std::getline(ss, tok, ',');  r.label = (int)std::stof(tok);
        // Col 3: name        (skip)
        std::getline(ss, tok, ',');
        // Cols 4-13: ax,ay,az,gx,gy,gz,f1,f2,f3,mag
        for (int i = 0; i < INPUT_SIZE; i++) { std::getline(ss, tok, ','); r.feat[i] = std::stof(tok); }
        // Cols 14-22: exp_logit_0..8
        for (int c = 0; c < NUM_CLASSES; c++) { std::getline(ss, tok, ','); r.exp_logit[c] = std::stof(tok); }
        rows.push_back(r);
    }
    csv.close();
    std::cout << "Loaded " << rows.size() << " rows from data_with_logits.csv\n\n";

    // ── Per-sample tracking ──────────────────────────────────────────────────
    int total = 0, top1_correct = 0, top2_correct = 0, hls_py_match = 0;
    float margin_min =  1e30f, margin_max = -1e30f, margin_sum = 0.0f;

    // HLS vs Python logit error tracking
    float logit_err_max = 0.0f;          // worst single-logit error seen
    float logit_err_sum = 0.0f;          // sum of per-window max errors
    float logit_err_per_class[NUM_CLASSES] = {}; // accumulated per-class
    int   logit_err_count_per_class[NUM_CLASSES] = {};

    // confusion[expected][predicted]
    int confusion[NUM_CLASSES][NUM_CLASSES] = {};

    float window[T_STEPS][INPUT_SIZE];
    float logits[NUM_CLASSES];           // HLS output (dequantized)
    float exp_logits[NUM_CLASSES];       // Python float reference
    float probs[NUM_CLASSES];

    std::cout << std::fixed << std::setprecision(4);

    size_t i = 0;
    while (i + T_STEPS <= rows.size()) {
        // Require all T_STEPS rows to share the same label
        int label = rows[i].label;
        bool uniform = true;
        for (size_t k = i; k < i + T_STEPS; k++)
            if (rows[k].label != label) { uniform = false; break; }
        if (!uniform) { i++; continue; }

        for (int t = 0; t < T_STEPS; t++)
            for (int f = 0; f < INPUT_SIZE; f++)
                window[t][f] = rows[i+t].feat[f];

        // Pull expected logits from first row of the window (all 30 rows are identical)
        for (int c = 0; c < NUM_CLASSES; c++)
            exp_logits[c] = rows[i].exp_logit[c];

        // ── Inference ────────────────────────────────────────────────────────
        int pred = run_inference(window, logits);
        softmax(logits, probs);
        total++;

        // ── Check 1: Top-1 accuracy ──────────────────────────────────────────
        bool top1_ok = (pred == label);
        if (top1_ok) top1_correct++;
        confusion[label][pred]++;

        // ── Check 2: Top-2 accuracy ──────────────────────────────────────────
        // Find the two highest logit indices
        int first = 0, second = 0;
        float v1 = -1e30f, v2 = -1e30f;
        for (int c = 0; c < NUM_CLASSES; c++) {
            if (logits[c] > v1) { v2 = v1; second = first; v1 = logits[c]; first = c; }
            else if (logits[c] > v2) { v2 = logits[c]; second = c; }
        }
        bool top2_ok = (label == first || label == second);
        if (top2_ok) top2_correct++;

        // ── Check 3: Confidence margin (winner - runner-up) ──────────────────
        float margin = v1 - v2;
        margin_sum += margin;
        if (margin < margin_min) margin_min = margin;
        if (margin > margin_max) margin_max = margin;

        // ── Check 4: Dead-output ─────────────────────────────────────────────
        float abs_max = 0.0f;
        for (int c = 0; c < NUM_CLASSES; c++)
            if (std::fabs(logits[c]) > abs_max) abs_max = std::fabs(logits[c]);
        bool dead = (abs_max < DEAD_THRESHOLD);

        // ── Check 5: Low-confidence ──────────────────────────────────────────
        bool low_conf = (margin < MARGIN_THRESHOLD);

        // ── Check 6: HLS vs Python logit error ───────────────────────────────
        float win_logit_err = 0.0f;
        int py_pred = 0;
        float py_best = -1e30f;
        for (int c = 0; c < NUM_CLASSES; c++) {
            float err = std::fabs(logits[c] - exp_logits[c]);
            if (err > win_logit_err) win_logit_err = err;
            if (err > logit_err_max) logit_err_max = err;
            if (exp_logits[c] > py_best) { py_best = exp_logits[c]; py_pred = c; }
        }
        if (pred == py_pred) hls_py_match++;
        logit_err_sum += win_logit_err;
        logit_err_per_class[label]  += win_logit_err;
        logit_err_count_per_class[label]++;

        // ── Sample header ────────────────────────────────────────────────────
        std::cout << "─────────────────────────────────────────────────────────\n";
        std::cout << "Sample " << total
                  << " | Label: " << label
                  << " | Pred: " << pred
                  << " (top-2: " << first << "," << second << ")"
                  << " | " << (top1_ok ? "TOP1 ✓" : "TOP1 ✗")
                  << " | " << (top2_ok ? "TOP2 ✓" : "TOP2 ✗") << "\n";

        // ── Logits row (HLS output) ──────────────────────────────────────────
        std::cout << "  HLS out :";
        for (int c = 0; c < NUM_CLASSES; c++)
            std::cout << " [" << c << "]=" << std::setw(8) << logits[c];
        std::cout << "\n";

        // ── Expected logits row (Python reference) ────────────────────────────
        std::cout << "  Py  ref :";
        for (int c = 0; c < NUM_CLASSES; c++)
            std::cout << " [" << c << "]=" << std::setw(8) << exp_logits[c];
        std::cout << "\n";

        // ── Per-logit error row ───────────────────────────────────────────────
        std::cout << "  Error   :";
        for (int c = 0; c < NUM_CLASSES; c++)
            std::cout << " [" << c << "]=" << std::setw(8) << std::fabs(logits[c] - exp_logits[c]);
        std::cout << "  (max=" << win_logit_err << ")\n";

        // ── Softmax row ──────────────────────────────────────────────────────
        std::cout << "  Softmax :";
        for (int c = 0; c < NUM_CLASSES; c++)
            std::cout << " [" << c << "]=" << std::setw(6) << probs[c];
        std::cout << "\n";

        // ── Margin + confidence ──────────────────────────────────────────────
        std::cout << "  Margin  : " << margin
                  << (low_conf ? "  ⚠ LOW CONFIDENCE (< " + std::to_string(MARGIN_THRESHOLD) + ")" : "")
                  << "\n";

        // ── Predicted class softmax probability ──────────────────────────────
        std::cout << "  P(pred) : " << probs[pred] * 100.0f << "%"
                  << "   P(label): " << probs[label] * 100.0f << "%\n";

        // ── Dead-output warning ───────────────────────────────────────────────
        if (dead)
            std::cout << "  ⚠ DEAD OUTPUT — all logits near zero (max |logit| = "
                      << abs_max << ")\n";

        i += T_STEPS;
    }

    // ── Summary ───────────────────────────────────────────────────────────────
    std::cout << "\n═════════════════════════ SUMMARY ═════════════════════════\n";
    std::cout << "  Top-1 accuracy : " << top1_correct << "/" << total
              << " (" << (100.0f * top1_correct / total) << "%)\n";
    std::cout << "  Top-2 accuracy : " << top2_correct << "/" << total
              << " (" << (100.0f * top2_correct / total) << "%)\n";
    std::cout << "  Margin  min=" << margin_min
              << "  max=" << margin_max
              << "  avg=" << (margin_sum / total) << "\n";

    // ── HLS vs Python logit error ─────────────────────────────────────────────
    std::cout << "\n  Logit error (HLS fixed-pt vs Python float reference):\n";
    std::cout << "    HLS/Py pred match: " << hls_py_match << "/" << total << " (" << (100.0f * hls_py_match / total) << "%)\n";
    std::cout << "    Global max error : " << logit_err_max << "\n";
    std::cout << "    Global avg error : " << (logit_err_sum / total) << "\n";
    std::cout << "    Per-class avg    :\n";
    for (int c = 0; c < NUM_CLASSES; c++) {
        if (logit_err_count_per_class[c] == 0) continue;
        std::cout << "      class " << c << " : "
                  << (logit_err_per_class[c] / logit_err_count_per_class[c]) << "\n";
    }

    // ── Confusion matrix ─────────────────────────────────────────────────────
    std::cout << "\n  Confusion matrix (rows=expected, cols=predicted):\n";
    std::cout << "       ";
    for (int c = 0; c < NUM_CLASSES; c++) std::cout << "  P" << c;
    std::cout << "\n";
    for (int r = 0; r < NUM_CLASSES; r++) {
        bool row_used = false;
        for (int c = 0; c < NUM_CLASSES; c++) if (confusion[r][c]) { row_used = true; break; }
        if (!row_used) continue;
        std::cout << "  E" << r << " : ";
        for (int c = 0; c < NUM_CLASSES; c++)
            std::cout << std::setw(3) << confusion[r][c] << " ";
        std::cout << "\n";
    }
    std::cout << "═══════════════════════════════════════════════════════════\n";

    // Vitis HLS expects 'return 0' for a passed testbench.
    // Instead of failing if the model mispredicts the label (which is normal ML behavior),
    // we should fail if the hardware implementation diverges significantly from Python.
    if (logit_err_max > 0.5f) {
        std::cerr << "FAIL: HLS implementation output diverges from Python reference (max err = " << logit_err_max << ").\n";
        return 1;
    }
    std::cout << "PASS: HLS implementation matches Python reference.\n";
    return 0;
}